AWSTemplateFormatVersion: '2010-09-09'
Description: MCP deployment on API Gateway and Lambda
Transform: AWS::Serverless-2016-10-31
Globals:
  Api:
    OpenApiVersion: 3.0.1
  Function:
    Layers:
      - arn:aws:lambda:ap-southeast-1:580247275435:layer:LambdaInsightsExtension:55
      - arn:aws:lambda:ap-southeast-1:753240598075:layer:LambdaAdapterLayerX86:25
      - !Ref dependencies
    MemorySize: !Ref fnMemory
    Runtime: python3.12
    Timeout: !Ref fnTimeout
    Tracing: Active
Parameters:
  apiStage:
    Type: String
  fnMemory:
    Type: Number
  fnTimeout:
    Type: Number
  dependencies:
    Type: String
Resources:
  # APIGW
  Api:
    Type: AWS::Serverless::Api
    Properties:
      Name: mcp-api-gateway
      AccessLogSetting:
        DestinationArn: !GetAtt ApiLogGroup.Arn
        Format: '{ "requestId":"$context.requestId", "ip": "$context.identity.sourceIp", "requestTime":"$context.requestTime", "httpMethod":"$context.httpMethod","routeKey":"$context.routeKey", "status":"$context.status","protocol":"$context.protocol", "responseLength":"$context.responseLength", "auth.status":"$context.authorizer.status", "auth.error":"$context.authorizer.error", "auth.token":"$context.authorizer.token", "auth.reason":"$context.authorizer.reason", "auth.simple":"$context.authorizer.simple", "auth.pversion":"$context.authorizer.pversion" }'
      StageName: !Ref apiStage
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: openapi.yaml
  ApiLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/apigateway/apigw-redshiftmcp-${Api}"
      RetentionInDays: 7
  # Lambda
  FnRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: cloudwatch-insights
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                Resource: '*'
        - PolicyName: cloudwatch-logs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogStreams
                Resource: 'arn:aws:logs:*:*:log-group:*:*'
        - PolicyName: xray
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - xray:PutTraceSegments
                  - xray:PutTelemetryRecords
                  - xray:GetSamplingRules
                  - xray:GetSamplingTargets
                  - xray:GetSamplingStatisticSummaries
                Resource: '*'
        - PolicyName: s3-access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource: '*'
        - PolicyName: bedrock-access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - bedrock:Converse
                Resource: '*'
        - PolicyName: dynamodb-access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:GetItem
                Resource: '*'
        - PolicyName: cloudwatch-access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cloudwatch:GetMetricStatistics
                Resource: '*'
  RedshiftFn:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: mcp-redshift
      CodeUri: ../redshift_mcpserver
      Handler: run.sh
      Role: !GetAtt FnRole.Arn
      Environment:
        Variables:
          AWS_LAMBDA_EXEC_WRAPPER: /opt/bootstrap
          PORT: 8000
          REDSHIFT_HOST: your-redshift-host
          REDSHIFT_PORT: your-redshift-port
          REDSHIFT_DATABASE: your-redshift-database
          REDSHIFT_USER: your-redshift-user
          REDSHIFT_PASSWORD: your-redshift-password
      Tags:
        application:group: example_group
        application:owner: example_owner
  FnLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${RedshiftFn}'
      RetentionInDays: 7
  FnPerm:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt RedshiftFn.Arn
      Principal: apigateway.amazonaws.com
      Action: lambda:InvokeFunction
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${Api}/*/*/*'
  # COT MCP Lambda
  CotFn:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: mcp-cot
      CodeUri: ../cot_mcpserver
      Handler: run.sh
      Role: !GetAtt FnRole.Arn
      Environment:
        Variables:
          AWS_LAMBDA_EXEC_WRAPPER: /opt/bootstrap
          PORT: 8000
          BUCKET: your-s3-bucket-name
          KEY: your-s3-object-key
          BEDROCK_REGION: your-bedrock-region
      Tags:
        application:group: example_group
        application:owner: example_owner
  CotFnLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${CotFn}'
      RetentionInDays: 7
  CotFnPerm:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt CotFn.Arn
      Principal: apigateway.amazonaws.com
      Action: lambda:InvokeFunction
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${Api}/*/*/*'
  # Monitor MCP Lambda
  MonitorFn:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: mcp-monitor
      CodeUri: ../monitor_mcpserver
      Handler: run.sh
      Role: !GetAtt FnRole.Arn
      Environment:
        Variables:
          AWS_LAMBDA_EXEC_WRAPPER: /opt/bootstrap
          PORT: 8000
          REDSHIFT_CLUSTER: your-redshift-cluster-name
      Tags:
        application:group: example_group
        application:owner: example_owner
  MonitorFnLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${MonitorFn}'
      RetentionInDays: 7
  MonitorFnPerm:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt MonitorFn.Arn
      Principal: apigateway.amazonaws.com
      Action: lambda:InvokeFunction
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${Api}/*/*/*'
Outputs:
  outApi:
    Value: !Ref Api
  outApiEndpoint:
    Value: !Sub 'https://${Api}.execute-api.${AWS::Region}.amazonaws.com/${apiStage}'
  outFn:
    Value: !Ref RedshiftFn
  outCotFn:
    Value: !Ref CotFn
  outMonitorFn:
    Value: !Ref MonitorFn
